export const LOCAL_STORAGE_KEYS = {
  FARCASTER_USER: "farcasterUser",
  // ... any other keys
}

export const DEFAULT_CAST = `gm Farcaster!

              
- Sent from my Neynar App`

export const PRODUCT_CATEGORIES = `Frames, Frames Tooling, Actions, Memecoins, Shitcoin, Trading, messaging, Wallets, Lending, API's, Clients, Attestations, Gambling, Transportation, DeFi, NFTs Marketplaces, Blockchain Gaming, DAOs, Identity, Social Graphs, Intent Graphs, Decentralized Storage, Marketplaces, Supply Chain, Voting, Identity, Dev Tools, Oracles, Bridges, Content Creation, Staking, Auth, Prediction Markets, IP, Advertising, Privacy, Energy, Healthcare, Education, Charity, Governance, Asset Management, Real Estate, Jobs, Insurance, Music, Freelancing, E-commerce, Ticketing, Reputation, Legal,Payments, Healthcare Records, Social Impact, Data Marketplace, Notaries, Domain Names, Agricultural, Weather, Browsers, Collectibles, RWA, Tokenization, Grants, Channels, Extensions`

type Categories = {
  [category: string]: Set<string>
}

// Define categories with keywords
export const PRODUCT_CATEGORIES_AS_SETS: Categories = {
  "🖼️ Frames": new Set([
    "frame",
    "Frame",
    "structure",
    "framework",
    "chassis",
    "skeleton",
  ]),
  "🛠️ Frames Tooling": new Set([
    "tool",
    "tooling",
    "instrument",
    "equipment",
    "apparatus",
  ]),
  "🏃 Actions": new Set([
    "action",
    "activity",
    "movement",
    "task",
    "operation",
  ]),
  "😂 Memecoins": new Set(["meme", "joke", "fun", "humor", "parody"]),
  "💩 Shitcoin": new Set([
    "shitcoin",
    "low-quality",
    "junk",
    "scam",
    "pump and dump",
  ]),
  "📈 Trading": new Set([
    "trade",
    "trading",
    "exchange",
    "buy",
    "sell",
    "market",
  ]),
  "💬 Messaging": new Set([
    "message",
    "messaging",
    "chat",
    "communication",
    "text",
  ]),
  "👛 Wallets": new Set([
    "wallet",
    "purse",
    "funds",
    "vault",
    "digital wallet",
  ]),
  "💸 Lending": new Set(["lend", "lending", "loan", "borrow", "credit"]),
  "🔌 API's": new Set([
    "api",
    "application programming interface",
    "endpoint",
    "interface",
    "integration",
  ]),
  "🤖 Bot's": new Set(["bot", "bot's", "robot", "automation", "script"]),
  "🎨 Art": new Set([
    "painting",
    "art",
    "graphic-art",
    "drawing",
    "artwork",
    "sketching",
    "painter",
  ]),
  "👥 Clients": new Set(["client", "customer", "user", "consumer", "patron"]),
  "📜 Attestations": new Set([
    "attest",
    "attestation",
    "proof",
    "verification",
    "certification",
  ]),
  "🎰 Gambling": new Set([
    "gamble",
    "gambling",
    "bet",
    "betting",
    "wager",
    "casino",
  ]),
  "🚆 Transportation": new Set([
    "transport",
    "transportation",
    "travel",
    "transit",
    "logistics",
  ]),
  "🌐 DeFi": new Set([
    "defi",
    "decentralized finance",
    "crypto",
    "yield-farming",
    "liquidity",
    "staking",
  ]),
  "🖼️ NFTs Marketplaces": new Set([
    "nft",
    "non-fungible token",
    "marketplace",
    "digital art",
    "collectible",
  ]),
  "🎮 Blockchain Gaming": new Set([
    "blockchain",
    "gaming",
    "crypto games",
    "play-to-earn",
    "metaverse",
  ]),
  "🏛️ DAOs": new Set([
    "dao",
    "decentralized autonomous organization",
    "governance",
    "community",
    "voting",
  ]),
  "🆔 Identity": new Set([
    "identity",
    "id",
    "identification",
    "credentials",
    "verification",
  ]),
  "🕸️ Social Graphs": new Set([
    "social",
    "graph",
    "network",
    "heat map",
    "heatmap",
    "connections",
  ]),
  "🎯 Intent Graphs": new Set([
    "intent",
    "graph",
    "purpose",
    "objective",
    "goal",
  ]),
  "🗄️ Decentralized Storage": new Set([
    "storage",
    "decentralized",
    "data",
    "cloud",
    "dstorage",
  ]),
  "🛒 Marketplaces": new Set([
    "marketplace",
    "market",
    "bazaar",
    "exchange",
    "platform",
  ]),
  "📦 Supply Chain": new Set([
    "supply",
    "chain",
    "logistics",
    "distribution",
    "inventory",
  ]),
  "🗳️ Voting": new Set(["vote", "voting", "election", "ballot", "poll"]),
  "🔧 Dev Tools": new Set([
    "dev tools",
    "development",
    "programming",
    "software",
    "coding",
  ]),
  "🔮 Oracles": new Set([
    "oracle",
    "data feed",
    "prediction",
    "forecast",
    "price feed",
  ]),
  "🌉 Bridges": new Set([
    "bridge",
    "bridging",
    "connection",
    "cross-chain",
    "interoperability",
  ]),
  "🎨 Content Creation": new Set([
    "content",
    "creation",
    "media",
    "production",
    "publishing",
  ]),
  "📃 Newsletter": new Set(["newsletter"]),
  "📚 Books": new Set(["books", "novels", "book"]),
  "💰 Staking": new Set(["stake", "staking", "investment", "yield", "rewards"]),
  "🔑 Auth": new Set([
    "auth",
    "authentication",
    "login",
    "verification",
    "access",
  ]),
  "🔮 Prediction Markets": new Set([
    "prediction",
    "market",
    "forecast",
    "betting",
    "speculation",
  ]),
  "©️ IP": new Set([
    "ip",
    "intellectual property",
    "rights",
    "patent",
    "trademark",
  ]),
  "📢 Advertising": new Set([
    "advertising",
    "ads",
    "promotion",
    "marketing",
    "campaign",
  ]),
  "🔒 Privacy": new Set([
    "privacy",
    "confidential",
    "security",
    "anonymity",
    "protection",
  ]),
  "⚡ Energy": new Set([
    "energy",
    "power",
    "electricity",
    "renewable",
    "sustainability",
  ]),
  "🏥 Healthcare": new Set([
    "healthcare",
    "health",
    "medicine",
    "medical",
    "wellness",
  ]),
  "🎓 Education": new Set([
    "education",
    "learning",
    "teaching",
    "school",
    "training",
  ]),
  "❤️ Charity": new Set([
    "charity",
    "donation",
    "philanthropy",
    "non-profit",
    "fundraising",
  ]),
  "🏛️ Governance": new Set([
    "governance",
    "government",
    "policy",
    "regulation",
    "administration",
  ]),
  "📈 Asset Management": new Set([
    "asset",
    "management",
    "investment",
    "portfolio",
    "wealth",
  ]),
  "🏠 Real Estate": new Set([
    "real estate",
    "property",
    "land",
    "housing",
    "estate",
  ]),
  "💼 Jobs": new Set(["job", "employment", "work", "career", "position"]),
  "🛡️ Insurance": new Set([
    "insurance",
    "coverage",
    "policy",
    "risk",
    "protection",
  ]),
  "🎵 Music": new Set(["music", "song", "melody", "audio", "track"]),
  "🙈 ZK": new Set(["zero-knowledge", "zk", "zk-snarks", "privacy proof"]),
  "💻 Freelancing": new Set([
    "freelance",
    "freelancing",
    "contract",
    "gig",
    "independent",
  ]),
  "🛍️ E-commerce": new Set([
    "e-commerce",
    "shopping",
    "online store",
    "retail",
    "commerce",
  ]),
  "🎟️ Ticketing": new Set([
    "ticket",
    "ticketing",
    "admission",
    "event",
    "entry",
  ]),
  "🌟 Reputation": new Set([
    "reputation",
    "credibility",
    "trust",
    "rating",
    "review",
  ]),
  "⚖️ Legal": new Set([
    "legal",
    "law",
    "regulation",
    "compliance",
    "jurisdiction",
  ]),
  "💳 Payments": new Set([
    "payment",
    "payments",
    "transaction",
    "transfer",
    "remittance",
  ]),
  "📋 Healthcare Records": new Set([
    "healthcare records",
    "medical records",
    "health records",
    "EHR",
    "EMR",
  ]),
  "🌍 Social Impact": new Set([
    "social impact",
    "impact",
    "community",
    "change",
    "development",
  ]),
  "📊 Data Marketplace": new Set([
    "data marketplace",
    "data",
    "marketplace",
    "exchange",
    "trading",
  ]),
  "✍️ Notaries": new Set([
    "notary",
    "notaries",
    "certification",
    "authentication",
    "verification",
  ]),
  "🌐 Domain Names": new Set([
    "domain",
    "domain names",
    "website",
    "url",
    "dns",
  ]),
  "🌾 Agricultural": new Set([
    "agriculture",
    "agricultural",
    "farming",
    "crop",
    "farm",
  ]),
  "🌦️ Weather": new Set([
    "weather",
    "climate",
    "forecast",
    "meteorology",
    "temperature",
  ]),
  "🌐 Browsers": new Set(["browser", "browsers", "web", "internet", "search"]),
  "🏺 Collectibles": new Set([
    "collectible",
    "collectibles",
    "collection",
    "antique",
    "rare",
  ]),
  "🏗️ RWA": new Set([
    "rwa",
    "real-world asset",
    "assets",
    "physical asset",
    "tangible asset",
  ]),
  "🔖 Tokenization": new Set([
    "token",
    "tokenization",
    "tokenize",
    "digital asset",
    "crypto token",
  ]),
  "💸 Grants": new Set(["grant", "grants", "funding", "subsidy", "endowment"]),
  "📡 Channels": new Set([
    "channel",
    "channels",
    "communication",
    "broadcast",
    "stream",
  ]),
  "➕ Extensions": new Set([
    "extension",
    "extensions",
    "add-on",
    "plugin",
    "module",
  ]),
}

export const dateOptions = ["24-hours", "7-days", "30-days", "ytd"]
